# Generated by Django 5.0.1 on 2024-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='book_image',
            field=models.ImageField(default='media/default_book_image.jpg', upload_to='media/'),
        ),
    ]
