# Generated by Django 5.0.1 on 2024-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_booksmodel_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='book_image',
            field=models.ImageField(default='default_book_image.jpg', upload_to='media/'),
        ),
    ]
