# Generated by Django 5.0.1 on 2024-02-05 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_booksmodel_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbookmodel',
            name='star_given',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=5)]),
        ),
    ]
